# Generated by Django 5.0.2 on 2024-03-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('app_auth', '0003_recruiters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiters',
            name='CompanyFK',
        ),
        migrations.AddField(
            model_name='recruiters',
            name='companies',
            field=models.ManyToManyField(to='Company.company'),
        ),
    ]
