# Generated by Django 5.0.2 on 2024-03-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('app_auth', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_auth.userprofile')),
            ],
        ),
    ]
