# Generated by Django 5.0.2 on 2024-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
