# Generated by Django 5.0.2 on 2024-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_alter_posts_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
