# Generated by Django 5.0.2 on 2024-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyImage',
            field=models.ImageField(default='default_company_image.png', upload_to='images/company_pics/'),
        ),
    ]
