# Generated by Django 5.0.2 on 2024-03-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_jobapplication_message_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
