# Generated by Django 5.0.2 on 2024-04-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0027_alter_posts_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
