# Generated by Django 5.0.2 on 2024-03-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('app_auth', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_auth.recruiters'),
        ),
    ]
