# Generated by Django 5.0.2 on 2024-03-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_posts_location'),
        ('app_auth', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_auth.moderators'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_auth.recruiters'),
        ),
    ]
