# Generated by Django 5.0.2 on 2024-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_posts_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Seniority',
            field=models.CharField(blank=True, choices=[('Junior/Intern', 'Junior/Intern'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior'), ('Team Lead', 'Team Lead')], null=True),
        ),
    ]
