# Generated by Django 5.0.2 on 2024-03-17 19:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0014_alter_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
