# Generated by Django 5.0.2 on 2024-03-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_remove_posts_users_applied_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_status',
        ),
    ]
