# Generated by Django 5.0.2 on 2024-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_jobapplication_postfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='Message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='files/resumes/'),
        ),
    ]
